# Datenstrom Yellow extension settings

Extension: Cloudforms
Version: 0.2.1
Description: Embed a form from a Nextcloud.
Developer: Liam Perlaki
Tag: feature
DownloadUrl: https://github.com/pfadfinder26/yellow-cloudforms/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/pfadfinder26/yellow-cloudforms
DocumentationLanguage: en, de
Published: 2026-09-28 14:27:21
Status: experimental
system/workers/cloudforms.php: cloudforms.php, create, update
